### ISSUE TITLE
Code for fine-tuning MAE on custom data

### ISSUE THREAD

**Issue by RaiAnant** [ir413/mvp#8]
I wanted to finetune the MAE on a custom dataset, after loading the pretrained weights of "in-the-wild" provided in the repo. Would it be possible to access your code for training MAE on the given dataset? Training code would be really helpful for not only getting weights for the decoder part of MAE, but also writing a fine tuning code.

Thanks!

**Comment by ir413** [comment]
Hi @RaiAnant, sorry for the late response. We did not release the MAE training code since the official MAE code is available [here](https://github.com/facebookresearch/mae). We suggest using the official MAE implementation for MAE pre-training and/or fine-tuning (models trained using that repo should be fully compatible with this repo; we use the same format). Hope this helps!
